# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7619fd4ef32dcc6bedd17a03ec76b06370719b723b5c82eaec1bb561cb6af8ac4add6e11e183e1009b68f911bd507f6b26f9e388d48665145c39bedb6ac2c47c

test:
  secret_key_base: f648c398ab436f34b3d8e7f744902a4268efcf52d95fa659d2ec31bda5e6a043ec9752504fc19dfa46946619545b3e8569e415a50e6ccbbfd0344058c0e1d047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
